[workspace]
members = [
        "coffee_lib",
        "coffee_github",
        "coffee_storage",
        "coffee_core",
        "coffee_cmd",
        "coffee_httpd",
        "coffee_plugin",
        "coffee_testing",
]
resolver = "2"
