[package]
name = "coffee_github"
version = "0.1.0"
edition = "2021"

[dependencies]
coffee_lib = { path = "../coffee_lib" }
coffee_storage = { path = "../coffee_storage" }
async-trait = "0.1.57"
tokio = { version = "1.24.2", features = ["fs"] }
git2 = "0.15.0"
log = "0.4.17"
env_logger = "0.9.3"
serde_yaml = "^0.9.0"
walkdir = "2.3.2"
