[package]
name = "reckless_github"
version = "0.1.0"
edition = "2021"

[dependencies]
reckless_lib = { path = "../reckless_lib" }
async-trait = "0.1.57"
tokio = { version = "1.22.0", features = ["full"] }
git2 = "0.15.0"
log = "0.4.17"
env_logger = "0.9.3"
glob = "0.3.0"
serde_yaml = "^0.9.0"
