[package]
name = "coffee_httpd"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
clap = "4.1.11"
coffee_core = { path = "../coffee_core" }
paperclip = { version = "0.8.0", features = ["actix4"] }
log = "0.4.17"
env_logger = "0.9.3"
