[book]
authors = ["Vincenzo Palazzo"]
language = "en"
multilingual = false
src = "src"
title = "Coffee Plugin Manager"
description = "Coffee is a flexible core lightning plugin manager."

[build]
build-dir = "doc-build"
create-missing = false

[preprocessor.index]

[preprocessor.links]

[output.html]
default-theme = "ayu"

[output.html.search]
limit-results = 15
